#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
require_once 'src/util/functions.php';

use Lectdark\command\Cmd;

$command = $argv[1] ?? ''; // El primer argumento es el comando (por ejemplo, 'make:base')
$args = array_slice($argv, 2); // Los demás argumentos (por ejemplo, 'usuario')

new Cmd($command, $args);